"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import africastalking
import os
from dotenv import load_dotenv


load_dotenv()


def _parse_csv_env(var_name: str, default: str = "") -> list[str]:
    """
    Return a comma-separated env var as a cleaned list with empty values removed.
    """
    raw_value = os.getenv(var_name, default)
    return [item.strip() for item in raw_value.split(",") if item.strip()]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-=0gcs$+4v7d%r1=uxe)1o^sg-8ci-rkxsfrcq)1vanhj3e6*0x",
)

DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'undeciphered-cisalpine-jefferey.ngrok-free.dev',  # add your exact ngrok URL (without https://)
]
ALLOWED_HOSTS = _parse_csv_env(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,undeciphered-cisalpine-jefferey.ngrok-free.dev",
)

# Application definition

AFRICASTALKING_USERNAME = 'BRIAN OKELLO'  # Often 'sandbox' for testing
AFRICASTALKING_API_KEY = 'atsk_8e547d02fca6e7dc6c414790f65161fd4ea91ea52628ad4593346c96292b122797dfdf63'

# Initialize the SDK
africastalking.initialize(AFRICASTALKING_USERNAME, AFRICASTALKING_API_KEY)

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'registration',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
]
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'ussd-sessions',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'

CORS_ALLOWED_ORIGINS = _parse_csv_env("CORS_ALLOWED_ORIGINS")
CORS_ALLOW_ALL_ORIGINS = DEBUG and not CORS_ALLOWED_ORIGINS


TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
TWILIO_WHATSAPP_NUMBER = 'whatsapp:+14155238886'