# Generated by Django 6.0.3 on 2026-04-07 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_applicant_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='phone_number',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^(0|\\+254|254)?[0-9]{9}$', 'Enter a valid Kenyan phone number (e.g., 0712345678, +254712345678)')]),
        ),
    ]
