# Generated by Django 6.0.3 on 2026-04-02 09:25

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+?254[0-9]{9}$', 'Enter a valid Kenyan phone number.')])),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('county', models.CharField(max_length=100)),
                ('voter_status', models.BooleanField(default=False)),
                ('registration_channel', models.CharField(choices=[('USSD', 'USSD'), ('WEBSITE', 'Website'), ('WHATSAPP', 'WhatsApp')], default='WEBSITE', max_length=20)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-registered_at'],
                'indexes': [models.Index(fields=['county'], name='registratio_county_73f716_idx'), models.Index(fields=['registration_channel'], name='registratio_registr_b5460a_idx')],
            },
        ),
    ]
